# -*- coding: utf-8 -*-
"""calculadora_pyt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186r0-c3v8Ni9D2my4eYzMxKJYN8dUp6X
"""

# Calculadora de división en Python ejercicio # 3 (imperativo)

try:
    num1 = float(input("Ingrese el primer numero: "))
    num2 = float(input("Ingrese el segundo numero: "))

    result = num1 / num2
    print("El resultado de la división es:", result)
except ZeroDivisionError:
    print("Error: No se puede dividir entre cero.")
except ValueError:
    print("Error: Entrada no valida, debe ingresar un numero.")