# -*- coding: utf-8 -*-
"""contraseña_pyt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186r0-c3v8Ni9D2my4eYzMxKJYN8dUp6X
"""

# Verificación de contraseña en Python (imperativo)

# Contraseña almacenada
password_guardada = "Candy2210"

# Pedir al usuario su contraseña
entrada = input("Ingrese la contraseña: ")

# Comparación sin distinguir mayúsculas/minúsculas
if entrada.lower() == password_guardada.lower():
    print("Las contraseñas coinciden.")
else:
    print("Las contraseñas no coinciden.")