# -*- coding: utf-8 -*-
"""Ingredientes_pyt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186r0-c3v8Ni9D2my4eYzMxKJYN8dUp6X
"""

# Ejercicio  9 Phyton : Pedido de Pizza

def main():
    print("¿Desea una pizza vegetariana? (si/no)")
    respuesta = input().strip().lower()

    if respuesta == "si":
        ingredientes = ["Pimiento", "Tofu"]
        vegetariana = True
    else:
        ingredientes = ["Pepperoni", "Jamon", "Salchicha"]
        vegetariana = False

    print("Elija un ingrediente adicional:")
    for i, ing in enumerate(ingredientes, start=1):
        print(f"{i}. {ing}")

    opcion = int(input("Ingrese el número del ingrediente: "))
    ingrediente_elegido = ingredientes[opcion - 1]

    print("\n--- Pedido final ---")
    print("Pizza vegetariana" if vegetariana else "Pizza no vegetariana")
    print(f"Ingredientes: Mozzarella, Salsa Tomate, {ingrediente_elegido}")

if __name__ == "__main__":
    main()