# -*- coding: utf-8 -*-
"""ingresos_pyt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186r0-c3v8Ni9D2my4eYzMxKJYN8dUp6X
"""

# Obligación fiscal en Python

# Pedir datos al usuario
edad = int(input("Ingrese su edad: "))
ingresos = float(input("Ingrese sus ingresos mensuales en COP: "))

# Verificar criterios de impuestos
if edad >= 18 and ingresos > 5000000:
    print("Usted debe pagar impuestos.")
else:
    print("Usted no tiene obligación de pagar impuestos.")