# -*- coding: utf-8 -*-
"""numpar_pyt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186r0-c3v8Ni9D2my4eYzMxKJYN8dUp6X
"""

# Verificador par o impar en Python ejericio #4 (imperativo)

numero = int(input("Ingrese un número entero: "))

if numero % 2 == 0:
    print("El numero es par.")
else:
    print("El numero es impar.")