# -*- coding: utf-8 -*-
"""Verific_edad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186r0-c3v8Ni9D2my4eYzMxKJYN8dUp6X
"""

# Verificador de edad legal en Python ejercicio 1( paradigma imperativo)

# Pedir al usuario su edad
edad = int(input("Ingrese su edad: "))

# Verificar si es mayor de edad
if edad >= 18:
    print("Usted es mayor de edad.")
else:
    print("Usted es menor de edad.")